# Generated by Django 4.1.3 on 2022-12-12 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_name', models.CharField(max_length=30, verbose_name='Badge name')),
                ('badge_desc', models.TextField(verbose_name='Badge description')),
                ('badge_photo', models.ImageField(upload_to='badgeimages', verbose_name='Badge photo')),
                ('badge_url', models.URLField(null=True, verbose_name='Badge link')),
                ('badge_upload_datetime', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
