# Generated by Django 4.1.3 on 2022-12-13 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='badge_type',
            field=models.CharField(choices=[('markscard', 'markscard'), ('certificate', 'certificate'), ('other', 'other')], default=2, max_length=20),
        ),
        migrations.AlterField(
            model_name='badge',
            name='badge_photo',
            field=models.ImageField(null=True, upload_to='badgeimages', verbose_name='Badge photo'),
        ),
    ]
